appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: ZUq4H61QO2iaEoa2vnzR7ifbF6T0LVSnG6ersl+ErAkcQkL4cNa54LFFkuTXUKvAteONyG/LNxORlgDRmPieToSABkrmFtAABnGo5ytkctK0Mpfb8xJz0gpOri1DgYSudjU3nn+pa9DpO7hkw9Bi0N6+cL5sPfGic54CBPBhazg3rKw9pzOneKt0i76tFwAEFLNNV+qZON2nY/KUlsKXzErtjQaOiQ+j0XyW6dZwSAfXa67HGYqiahKOMkSHuU1c109Vwv3GGVoKWsUgSELP5g7l3hv63gS6bNPCC9h0YQRh2BL7RNjaEnsS5fFv27bKRPqwzeh71QQel8OsziawXt21Jc+Qo0CcUztbtH3PYUDyRXg6ptyn24ZzLBHa3sapPF8+y91g0+wMH5iRFf4x+S/Yuy/hmcvQ5GT2BG4h7e1LehLrEA7xYoBnBCLYLFAze3+KLCZvt9psTJA7AkHp2tR1nq/lXXUybRQILdbz4q2HC+wTwYTSEalE7Wruv3eVk6U5JxQW6dgZ2Zzj93SJb/0FdJlSgTOkCE0Acn8ldEkf1lnYWE8Y0okP8kVE/ECOdhIJfKuYz5gN3JSWrGB/8GpYgrQjbkO8hfuB/Y8ElZpC43YUzYpaMh/N/e+Ob6m21C1LbiMakrh58qDRkB76lnBaFuqngL957g/7VBh0n9o=
